import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createWorld,makeBuilding} from '../src/model.js';
import {districtKindOf,districtGrid,settlementTopology} from '../src/systems/logistics.js';
const data=Object.fromEntries(await Promise.all(['world','troops','items','abilities','buildings','missions','quests'].map(async n=>[n,JSON.parse(await readFile(new URL(`../data/${n}.json`,import.meta.url)))])));
test('districts: farm cluster reads farming, old keys untouched',()=>{
  const w=createWorld(data);
  const before=w.buildings.filter(b=>b.hp>0&&b.remaining<=0&&/mine|forge|smelt|armory|sawmill/.test(b.type)).map(b=>b.id);
  const mine=makeBuilding('mine',30,30,data);
  w.buildings.push(makeBuilding('farm',2,2,data),makeBuilding('farm',4,3,data),mine);
  assert.equal(districtKindOf('farm'),'farming');
  const g=districtGrid(w,data);
  assert.ok(g.cells.some(c=>c.kind==='farming'&&c.count>=2));
  assert.deepEqual(settlementTopology(w,data).districts.industrial,[...before,mine.id]);
});
test('districts: civic/market keys, 30s cache bucketing, detached returns',()=>{
  const w=createWorld(data);
  w.buildings=[];
  const chapel=makeBuilding('chapel',2,2,data),school=makeBuilding('schoolroom',3,2,data),market=makeBuilding('market',30,30,data),store=makeBuilding('storehouse',31,30,data);
  w.buildings.push(chapel,school,market,store);
  assert.equal(districtKindOf('chapel'),'civic');
  assert.equal(districtKindOf('market-square'),'market');
  assert.equal(districtKindOf('storehouse'),'market');
  assert.equal(districtKindOf('grand-granary'),'market');
  assert.equal(districtKindOf('cottage'),'residential');
  assert.equal(districtKindOf('barracks'),'military');
  assert.equal(districtKindOf('trap'),null);
  assert.equal(districtKindOf('sawmill'),'industrial');
  assert.equal(districtKindOf('bell-tower'),'civic');
  assert.equal(districtKindOf('dawn-gate'),'civic');
  const t=settlementTopology(w,data);
  assert.deepEqual(t.districts.civic,[chapel.id,school.id]);
  assert.deepEqual(t.districts.market,[market.id,store.id]);
  assert.deepEqual(t.districts.trade,[market.id]);
  assert.equal(t.cells.find(c=>c.cx===0&&c.cy===0).kind,'civic');
  w.elapsed=10;
  const a=districtGrid(w,data),b=districtGrid(w,data);
  assert.deepEqual(a,b);
  assert.notEqual(a,b);
  assert.notEqual(a.cells,b.cells);
  w.buildings.push(makeBuilding('chapel',4,4,data));
  assert.deepEqual(districtGrid(w,data),b);
  w.elapsed=31;
  const c=districtGrid(w,data);
  assert.ok(c.cells.find(x=>x.cx===0&&x.cy===0).count>b.cells.find(x=>x.cx===0&&x.cy===0).count);
  c.cells.length=0;
  c.cells.push({cx:9,cy:9,kind:'market',count:9});
  const d=districtGrid(w,data);
  assert.ok(d.cells.some(x=>x.kind==='civic'));
  assert.ok(!d.cells.some(x=>x.cx===9&&x.cy===9));
  const t2=settlementTopology(w,data);
  t2.districts.civic.length=0;
  t2.cells.length=0;
  assert.ok(settlementTopology(w,data).districts.civic.length>0);
  assert.ok(settlementTopology(w,data).cells.length>0);
});
