import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {Game} from '../src/game.js';
import {makeBuilding} from '../src/model.js';
import {recordTravel} from '../src/systems/trails.js';
import {tickAutomation} from '../src/systems/automation.js';
const data=Object.fromEntries(await Promise.all(['world','buildings','troops','items','abilities','missions','quests'].map(async n=>[n,JSON.parse(await readFile(new URL(`../data/${n}.json`,import.meta.url)))])));
test('LK slice: idle builder takes gated road job, raids pause it',()=>{
  const g=new Game(data);g.state.vlevel=9;const w=g.state.world;
  w.buildings.push(makeBuilding('stone-road',18,15,data,3));
  for(let i=0;i<250;i++)recordTravel(w,data,2.25,8.25,8.25,8.25);
  w.resources={...w.resources,wood:1000,gold:1000,lumber:1000};
  const b=w.troops.find(u=>data.troops[u.type]?.role==='builder');
  assert.ok(b,'needs a builder');
  tickAutomation(g,0.1);
  assert.equal(typeof b.builderTask?.kind,'string');
  assert.equal(b.builderTask.kind,'road');
  w.raidPending={timer:3,count:2};
  tickAutomation(g,2.1);
  assert.equal(b.builderTask,undefined);
});
