import {MeshScene} from '../src/scene3d.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createWorld,makeBuilding,makeUnit} from '../src/model.js';
import {tickLogistics,visualHauls,haulFor,chooseDestination,logisticsMetrics,refinementEfficiency,settlementTopology,requestCaravan,visualCaravans} from '../src/systems/logistics.js';
import {buildRoad,roadQuote,ROAD_SPEED} from '../src/systems/roads.js';
import {trailMultiplier,recordTravel,tickTrails} from '../src/systems/trails.js';
import {centralRoom,storageCap} from '../src/systems/storage.js';
import {exportSave,importSaveBlob} from '../src/storage.js';
import {tickEconomy} from '../src/systems/economy.js';
import {tickRefine} from '../src/systems/crafting.js';
import {Game} from '../src/game.js';
const data=Object.fromEntries(await Promise.all(['world','buildings','troops','items','abilities','missions','quests','expansion','biomes'].map(async n=>[n,JSON.parse(await readFile(new URL(`../data/${n}.json`,import.meta.url)))])));
function fixture(){const w=createWorld(data);for(const t of w.tiles)t.claimed=true;w.buildings=[];w.troops=[];w.elapsed=400;w.resources={wood:100,food:100,gold:100,lumber:100,flour:100,bread:0};const farm=makeBuilding('farm',4,4,data),store=makeBuilding('storehouse',11,4,data),worker=makeUnit('builder',data);farm.harvestBonus=80;worker.x=3.5;worker.y=4.5;worker.traits=[];w.buildings.push(farm,store);w.troops.push(worker);return {w,farm,store,worker};}
function run(w,n=800){for(let i=0;i<n;i++){w.elapsed+=.05;tickLogistics(w,data,.05);}}
test('producer hauls move a worker and bank exactly the source decrease',()=>{const {w,farm,worker}=fixture(),start=w.resources.food;tickLogistics(w,data,.05);assert.equal(visualHauls(w).length,1);assert.equal(haulFor(worker).sourceId,farm.id);assert.equal(farm.harvestBonus,80);run(w);const landed=w.resources.food-start;assert.ok(landed>0);assert.equal(landed+farm.harvestBonus,80);assert.ok(worker.x>3.5);});
test('manual posts, orders, cargo and emergency duty are never borrowed',()=>{for(const prop of [{workplace:'manual',manualPost:true},{order:{kind:'hold'}},{carry:4},{emergency:'flee'},{expedition:{}}]){const {w,worker}=fixture();Object.assign(worker,prop);tickLogistics(w,data,.05);assert.equal(visualHauls(w).length,0);for(const [k,v] of Object.entries(prop))assert.deepEqual(worker[k],v);}});
test('strong backs carry more; hard workers keep their traits',()=>{const {w,worker}=fixture();worker.traits=['strong','hard_worker'];tickLogistics(w,data,.05);assert.equal(haulFor(worker).amount,30);assert.equal(haulFor(worker).cart,true);});
test('full shared storage leaves all goods at their source and resumes after spending',()=>{const {w,farm}=fixture();w.resources.food=storageCap(w,data,'food');run(w,80);assert.equal(farm.harvestBonus,80);assert.equal(visualHauls(w).length,0);w.resources.food-=30;run(w);assert.equal(w.resources.food+farm.harvestBonus,storageCap(w,data,'food')+50);});
test('ruined destination, player order and reload never lose reserved goods',()=>{for(const mode of ['ruin','order','reload']){const {w,farm,store,worker}=fixture();tickLogistics(w,data,.05);run(w,60);if(mode==='ruin')store.hp=0;else if(mode==='order')worker.order={kind:'hold'};else{const back=importSaveBlob(exportSave({world:w,home:null,mission:null,completed:[],unlocks:[],questsCompleted:[],xp:0}),data);assert.equal(back.ok,true);assert.equal(back.state.world.buildings[0].harvestBonus+w.resources.food,180);continue;}run(w,2);assert.equal(farm.harvestBonus+w.resources.food,180);assert.equal(haulFor(worker),null);}});
test('unreachable enclosed storage never teleports goods through walls',()=>{const {w,farm,store}=fixture();for(let y=3;y<=6;y++)for(let x=10;x<=13;x++)if(x===10||x===13||y===3||y===6)w.buildings.push(makeBuilding('wall',x,y,data));tickLogistics(w,data,.05);assert.equal(chooseDestination(w,data,farm,'food'),null);assert.equal(farm.harvestBonus,80);});
test('destination scan prefers a nearby compatible hub deterministically',()=>{const {w,farm}=fixture();const near=makeBuilding('grand-granary',7,4,data);w.buildings.push(near);tickLogistics(w,data,.05);assert.equal(visualHauls(w)[0].destinationId,near.id);assert.equal(chooseDestination(w,data,farm,'food').building.id,near.id);assert.equal(chooseDestination(w,data,farm,'frostwood').building.type,'storehouse');});
test('queue, cart and route caches stay bounded with 150 idle hands',()=>{const {w}=fixture();w.buildings=[];w.troops=[];for(let i=0;i<48;i++){const b=makeBuilding('farm',2+i%12*4,2+Math.floor(i/12)*5,data);b.harvestBonus=200;w.buildings.push(b);}w.buildings.push(makeBuilding('storehouse',24,30,data));for(let i=0;i<150;i++){const u=makeUnit('builder',data);u.x=1.5;u.y=1.5+i%30;w.troops.push(u);}run(w,300);const m=logisticsMetrics(w);assert.ok(m.activeJobs<=24);assert.ok(m.visibleCarts<=10);assert.ok(m.routeCache<=48);assert.ok(m.intervalPathCalculations<=8);});
test('route reuse performs no path calculations between planning intervals',()=>{const {w}=fixture();tickLogistics(w,data,.05);const n=logisticsMetrics(w).pathCalculations;run(w,20);assert.equal(logisticsMetrics(w).pathCalculations,n);});
test('formalization quotes before spending, preserves trails, paving persists without traffic',()=>{const {w}=fixture();w.buildings.push(makeBuilding('stone-road',18,15,data,3));w.resources={wood:1000,gold:1000,lumber:1000,food:100};for(let i=0;i<250;i++)recordTravel(w,data,2.25,8.25,8.25,8.25);const trails=structuredClone(w.trails),q=roadQuote(w,data,'4,16');assert.ok(q.cells.length>0&&q.cells.length<=64);const wood=w.resources.wood;assert.equal(buildRoad(w,data,'4,16').ok,true);assert.equal(w.resources.wood,wood-q.cost.wood);assert.deepEqual(w.trails,trails);assert.equal(trailMultiplier(w,2.25,8.25),1.18);assert.equal(buildRoad(w,data,'4,16',2).ok,true);w.elapsed+=1e7;tickTrails(w);assert.equal(trailMultiplier(w,2.25,8.25),1.3);assert.equal(trailMultiplier(w,2.25,8.25,false),1);});
test('old v14 saves preserve all ledgers and trails with exactly one road migration',()=>{const {w}=fixture();w.trails={'4,16':[45,w.elapsed]};delete w.roads;const value={version:14,world:w,home:structuredClone(w),mission:null,completed:['first-harvest'],unlocks:['tower'],questsCompleted:[],xp:100,multiplayer:{friends:['test']}};const before=structuredClone(value),back=importSaveBlob(JSON.stringify(value),data);assert.ok(back.ok);assert.equal(back.state.version,15);assert.deepEqual(back.state.world.resources,before.world.resources);assert.deepEqual(back.state.world.trails,before.world.trails);assert.deepEqual(back.state.world.roads,{});assert.deepEqual(back.state.home.roads,{});assert.deepEqual(back.state.multiplayer,before.multiplayer);assert.deepEqual(back.state.completed,before.completed);});
test('Collect Ready during a loaded haul cannot double-bank the batch',()=>{const {w,farm}=fixture(),g=new Game(data);g.state.world=w;g.paused=false;tickLogistics(w,data,.05);run(w,70);const before=w.resources.food;assert.equal(g.collectAll().food,80);run(w,800);assert.equal(w.resources.food,before+80);assert.equal(farm.harvestBonus,0);});
test('workshops receive supply visits while their manual crew keeps working',()=>{const {w,worker}=fixture();w.buildings[0].harvestBonus=0;const shop=makeBuilding('sawmill',5,11,data),crew=makeUnit('sawyer',data);crew.workplace=shop.id;crew.manualPost=true;w.buildings.push(shop);w.troops.push(crew);run(w,1200);assert.equal(crew.workplace,shop.id);assert.ok(refinementEfficiency(w,data,shop)>=1);const input=w.resources.wood;tickRefine(w,data,1);assert.ok(w.resources.wood<input);assert.ok(w.resources.lumber>100);});
test('Great Works improve logistics gently and expose detached district hooks',()=>{const {w}=fixture();const shop=makeBuilding('sawmill',5,11,data);w.buildings.push(shop);tickLogistics(w,data,.05);const old=refinementEfficiency(w,data,shop);w.buildings.push(makeBuilding('forge-quarter',8,11,data,6));run(w,50);assert.ok(refinementEfficiency(w,data,shop)>old);assert.ok(refinementEfficiency(w,data,shop)<=1.15);const t=settlementTopology(w,data);assert.ok(t.districts.industrial.includes(shop.id));t.districts.industrial.length=0;assert.ok(settlementTopology(w,data).districts.industrial.includes(shop.id));});
test('caravans are capped, arrive, unload and depart without changing trade inventory',()=>{const {w}=fixture();w.buildings.push(makeBuilding('market',8,10,data));const before=structuredClone(w.resources);assert.equal(requestCaravan(w,data),true);assert.equal(requestCaravan(w,data),false);run(w,3500);assert.equal(visualCaravans(w).length,0);assert.equal(w.resources.food+w.buildings[0].harvestBonus,before.food+80);});

test('overview LOD reduces coplanar subdivisions without changing mesh bounds',()=>{const r={width:390,height:844,cam:{yaw:Math.PI/4,pitch:.8,zoom:1.1},project:(x,y,z=0)=>({x:100+x*20,y:100+y*10-z*10}),depth:(x,y,z)=>x+y+z};const close=new MeshScene(r),overview=new MeshScene(r);close.box(0,0,0,3,3,3,'#987046');overview.subdivision=.8;overview.box(0,0,0,3,3,3,'#987046');assert.ok(overview.faces.length<close.faces.length*.5);for(const scene of [close,overview]){const coords=scene.faces.flatMap(f=>f.vertices).flat();assert.equal(Math.min(...coords),0);assert.equal(Math.max(...coords),3);}});
