import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createWorld,makeBuilding,makeUnit} from '../src/model.js';
import {Game} from '../src/game.js';
import {tickRefine} from '../src/systems/crafting.js';
import {tickLogistics,visualHauls,haulFor} from '../src/systems/logistics.js';
import {OUTPUT_CAP,outputAmount,fallbackOutputs} from '../src/systems/refiner-output.js';
import {storageCap} from '../src/systems/storage.js';
import {exportSave,importSaveBlob} from '../src/storage.js';
import {reserveCollectible,collectionTotals} from '../src/resources.js';
const data=Object.fromEntries(await Promise.all(['world','buildings','troops','items','abilities','missions','quests'].map(async n=>[n,JSON.parse(await readFile(new URL(`../data/${n}.json`,import.meta.url)))])));
function fixture(){const w=createWorld(data);for(const t of w.tiles)t.claimed=true;w.buildings=[];w.troops=[];w.elapsed=400;w.resources={wood:1000,food:100,gold:100,lumber:0};const shop=makeBuilding('sawmill',4,4,data),store=makeBuilding('storehouse',10,4,data),crew=makeUnit('sawyer',data),hand=makeUnit('builder',data);crew.workplace=shop.id;crew.manualPost=true;crew.traits=[];hand.traits=[];hand.x=3.5;hand.y=4.5;w.buildings.push(shop,store);w.troops.push(crew,hand);return {w,shop,store,crew,hand};}
function run(w,n){for(let i=0;i<n;i++){w.elapsed+=.05;tickLogistics(w,data,.05);}}
test('physical recipe output remains at its workshop until the real batch unloads',()=>{const {w,shop,crew,hand}=fixture();const made=tickRefine(w,data,20,true).lumber;assert.ok(made>4);assert.equal(w.resources.lumber,0);assert.equal(outputAmount(shop,'lumber'),made);assert.equal(w.gathered.lumber,0);tickLogistics(w,data,.05);assert.equal(haulFor(hand).kind,'output');run(w,600);assert.ok(w.resources.lumber>0);assert.equal(w.resources.lumber+outputAmount(shop,'lumber'),made);assert.equal(w.gathered.lumber,w.resources.lumber);assert.equal(crew.workplace,shop.id);});
test('output capacity reserves shared room without spending inputs that cannot become goods',()=>{const {w,shop}=fixture();w.resources.lumber=storageCap(w,data,'lumber')-10;tickRefine(w,data,1000,true);assert.equal(outputAmount(shop,'lumber'),10);const wood=w.resources.wood;tickRefine(w,data,1000,true);assert.equal(w.resources.wood,wood);w.resources.lumber=0;tickRefine(w,data,1000,true);assert.equal(outputAmount(shop,'lumber'),OUTPUT_CAP);});
test('Collect Ready can bank workshop output during a loaded trip without double banking',()=>{const {w,shop,hand}=fixture();const made=tickRefine(w,data,100,true).lumber;tickLogistics(w,data,.05);for(let i=0;i<200&&!haulFor(hand)?.loaded;i++)run(w,1);assert.equal(haulFor(hand).loaded,true);const g=new Game(data);g.state.world=w;g.paused=false;assert.ok(reserveCollectible(shop,data.buildings.sawmill));assert.equal(collectionTotals(w,data).lumber,Math.floor(made));const landed=g.collectAll().lumber;assert.equal(landed,Math.floor(made));run(w,800);assert.ok(Math.abs(w.resources.lumber+outputAmount(shop,'lumber')-made)<1e-8);assert.ok(Math.abs(w.gathered.lumber-w.resources.lumber)<1e-8);});
test('interrupted output trips and save reload preserve goods including ruined workshops',()=>{const {w,shop,hand}=fixture();const made=tickRefine(w,data,100,true).lumber;tickLogistics(w,data,.05);hand.order={kind:'hold'};run(w,2);assert.equal(visualHauls(w).length,0);shop.hp=0;const back=importSaveBlob(exportSave({world:w,home:null,mission:null,completed:[],unlocks:[],questsCompleted:[],xp:0}),data);assert.ok(back.ok);assert.equal(outputAmount(back.state.world.buildings[0],'lumber'),made);assert.equal(back.state.world.resources.lumber,0);});
test('no idle hauler or reachable hub never deadlocks refinement; full storage retains every unit',()=>{const {w,shop}=fixture();w.troops.pop();const made=tickRefine(w,data,100,true).lumber;tickLogistics(w,data,.05);w.resources.lumber=storageCap(w,data,'lumber');run(w,640);assert.equal(outputAmount(shop,'lumber'),made);w.resources.lumber-=made;run(w,50);assert.ok(outputAmount(shop,'lumber')<1e-8);assert.equal(w.resources.lumber,storageCap(w,data,'lumber'));});
test('v14 migration adds empty workshop buffers; existing buffer saves never reset or accept invalid amounts',()=>{const {w,shop}=fixture(),value={version:14,world:w,home:null,mission:null,completed:[],unlocks:[],questsCompleted:[],xp:0};const migrated=importSaveBlob(JSON.stringify(value),data);assert.ok(migrated.ok);assert.deepEqual(migrated.state.world.buildings[0].outputReserve,{});shop.outputReserve={lumber:17};shop.outputSince=390;value.version=15;assert.equal(importSaveBlob(JSON.stringify(value),data).state.world.buildings[0].outputReserve.lumber,17);shop.outputReserve.lumber=-1;assert.equal(importSaveBlob(JSON.stringify(value),data).ok,false);});
test('fallback respects active deliveries and individual workshop collection uses the storage gate',()=>{const {w,shop}=fixture();tickRefine(w,data,20,true);w.elapsed+=31;fallbackOutputs(w,data,shop,true);assert.equal(w.resources.lumber,0);const g=new Game(data);g.state.world=w;g.paused=false;assert.ok(g.harvest(shop.id)>0);assert.ok(outputAmount(shop,'lumber')<1);});
