import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createWorld,makeBuilding,makeUnit} from '../src/model.js';
import {tickLogistics,visualHauls,supplyDiagnostics,logisticsMetrics,refinementEfficiency} from '../src/systems/logistics.js';
import {supplyPriorities,workshopSupplyStatus} from '../src/systems/supply-priority.js';
import {storageCap} from '../src/systems/storage.js';
import {OUTPUT_CAP} from '../src/systems/refiner-output.js';
import {refreshStewardBudget} from '../src/systems/steward-budget.js';
import {tickRefine} from '../src/systems/crafting.js';
import {Game} from '../src/game.js';
import {supplyReadout} from '../src/supply-ui.js';
const data=Object.fromEntries(await Promise.all(['world','buildings','troops','items','abilities','missions','quests','expansion','biomes'].map(async n=>[n,JSON.parse(await readFile(new URL(`../data/${n}.json`,import.meta.url)))])));
function fixture(){const w=createWorld(data);w.buildings=[];w.troops=[];w.enemies=[];w.elapsed=400;w.resources={wood:100,food:0,gold:100,lumber:0,flour:0,bread:0,plate:0,frostwood:0};const store=makeBuilding('storehouse',15,15,data),farm=makeBuilding('farm',4,4,data),mine=makeBuilding('mine',4,9,data),worker=makeUnit('builder',data);farm.harvestBonus=80;mine.harvestBonus=80;worker.x=3.5;worker.y=4.5;w.buildings=[mine,farm,store];w.troops=[worker];return {w,store,farm,mine,worker};}
function run(w,n=1000){for(let i=0;i<n;i++){w.elapsed+=.05;tickLogistics(w,data,.05);}}
function shop(w,type,x=8,y=8){const b=makeBuilding(type,x,y,data),u=makeUnit(data.buildings[type].workplace,data);u.workplace=b.id;w.buildings.push(b);w.troops.push(u);return b;}
test('meal shortages win the first spare hand over earlier surplus producers',()=>{const {w,farm}=fixture();tickLogistics(w,data,.05);assert.equal(visualHauls(w)[0].sourceId,farm.id);assert.equal(supplyDiagnostics(w,data).needs[0].priority,100);});
test('recovery and equipment reserves identify shortages without changing balances',()=>{const {w}=fixture();const b=w.buildings[2];b.hp=1;w.resources.wood=0;w.automation={reserves:{plate:30}};const before=structuredClone(w.resources),needs=supplyPriorities(w,data);assert.equal(needs.get('wood').priority,90);assert.ok(needs.get('wood').missing>0);assert.equal(needs.get('plate').priority,50);assert.deepEqual(w.resources,before);});
test('staffed bread chain pulls demand through flour to food',()=>{const {w}=fixture();shop(w,'bakery');shop(w,'mill',11,8);const n=supplyPriorities(w,data);assert.ok(n.get('bread').missing>0);assert.ok(n.get('flour').missing>0);assert.ok(n.get('food').reasons.includes('Workshop supply chain'));});
test('unworked workshops never pull phantom ingredient demand',()=>{const {w}=fixture();w.buildings.push(makeBuilding('bakery',8,8,data),makeBuilding('mill',11,8,data));const n=supplyPriorities(w,data);assert.equal(n.has('flour'),false);});
test('Steward queued baskets count cumulative material needs and retain protected funds',()=>{const {w}=fixture(),g=new Game(data);g.state.world=w;w.steward={enabled:true};w.resources.wood=5;refreshStewardBudget(g,[],[{id:'a',label:'Sawmill',cost:{wood:30},status:'Waiting'},{id:'b',label:'Granary',cost:{wood:40},status:'Waiting'}]);const n=supplyPriorities(w,data).get('wood');assert.equal(n.target,70);assert.equal(n.missing,65);assert.equal(w.resources.wood,5);});
test('urgent raw output routes to a needing workshop instead of the nearby warehouse',()=>{const {w,farm,store}=fixture();store.x=6;store.y=4;const mill=shop(w,'mill',10,4);shop(w,'bakery',13,5);tickLogistics(w,data,.05);const job=visualHauls(w).find(j=>j.sourceId===farm.id);assert.equal(job.destinationId,mill.id);});
test('full workshop buffers suppress input trips and report the cause',()=>{const {w}=fixture();w.buildings=w.buildings.filter(b=>b.type==='storehouse');const b=shop(w,'sawmill');b.outputReserve={lumber:OUTPUT_CAP};w.resources.wood=100;tickLogistics(w,data,.05);assert.ok(!visualHauls(w).some(j=>j.kind==='supply'&&j.destinationId===b.id));assert.equal(supplyDiagnostics(w,data).workshops.find(x=>x.buildingId===b.id).state,'output');});
test('workshop diagnostics distinguish missing crew, raw inputs, output room and healthy work',()=>{const {w}=fixture(),b=makeBuilding('sawmill',8,8,data);assert.equal(workshopSupplyStatus(w,data,b,0).state,'workers');w.resources.wood=0;assert.deepEqual(workshopSupplyStatus(w,data,b,1).missing,['wood']);w.resources.wood=10;assert.equal(workshopSupplyStatus(w,data,b,1).state,'working');w.resources.lumber=storageCap(w,data,'lumber');assert.equal(workshopSupplyStatus(w,data,b,1).state,'output');b.hp=0;assert.equal(workshopSupplyStatus(w,data,b,1).state,'unavailable');});
test('manual assignments and construction workers are not borrowed for urgent hauls',()=>{const {w,worker,farm}=fixture();worker.workplace='manual';tickLogistics(w,data,.05);assert.equal(visualHauls(w).length,0);assert.equal(farm.harvestBonus,80);assert.match(supplyDiagnostics(w,data).issues[0].reason,/No spare/);});
test('alarm prevents new trips and cancels existing reservations without losing material',()=>{const {w,farm}=fixture();tickLogistics(w,data,.05);assert.ok(visualHauls(w).length);w.raidPending={timer:25};run(w,50);assert.equal(visualHauls(w).length,0);assert.equal(farm.harvestBonus,80);assert.ok(supplyDiagnostics(w,data).issues.every(i=>i.reason.includes('raid safety')));});
test('full storage reports its bottleneck without losing or moving inventory',()=>{const {w,farm}=fixture();w.resources.food=storageCap(w,data,'food');tickLogistics(w,data,.05);assert.equal(farm.harvestBonus,80);assert.ok(supplyDiagnostics(w,data).issues.some(i=>i.resource==='food'&&i.reason==='Shared storage full'));});
test('isolated source explains unreachable routes and never teleports the load',()=>{const {w,farm}=fixture();for(let x=3;x<=6;x++)for(let y=3;y<=6;y++)if(x===3||x===6||y===3||y===6)w.buildings.push(makeBuilding('wall',x,y,data));run(w,50);assert.equal(farm.harvestBonus,80);assert.ok(supplyDiagnostics(w,data).issues.some(i=>/reachable/.test(i.reason)));});
test('delivery diagnostics are detached and capped; readouts name shortages and project benefits',()=>{const {w}=fixture();w.troops[0].order={kind:'hold'};w.buildings.push(makeBuilding('grand-granary',20,10,data,6));tickLogistics(w,data,.05);const a=supplyDiagnostics(w,data);a.needs[0].reasons.length=0;a.issues.length=0;const b=supplyDiagnostics(w,data);assert.ok(b.needs[0].reasons.length>0);assert.ok(b.issues.length>0&&b.issues.length<=8);assert.match(supplyReadout(w,data),/Delivery bottlenecks/);assert.match(supplyReadout(w,data),/Granary \+18%/);});
test('supply visits preserve inventory while producing a real throughput benefit',()=>{const {w}=fixture();w.buildings=w.buildings.filter(b=>b.type==='storehouse');const b=shop(w,'sawmill');w.resources.wood=100;const before=structuredClone(w.resources);for(let i=0;i<2000&&logisticsMetrics(w).supplyVisits===0;i++)run(w,1);assert.ok(logisticsMetrics(w).supplyVisits>0);assert.deepEqual(w.resources,before);assert.ok(refinementEfficiency(w,data,b)>1);const stock=w.resources.wood;tickRefine(w,data,1,true);assert.ok(w.resources.wood<stock);assert.ok(b.outputReserve.lumber>0);});
test('two workshops sharing one supply hub eventually both receive visits',()=>{const {w}=fixture();w.resources.food=200;w.buildings=w.buildings.filter(b=>b.type==='storehouse');const a=shop(w,'sawmill',10,10),b=shop(w,'sawmill',10,20);run(w,2500);assert.ok(refinementEfficiency(w,data,a)>1);assert.ok(refinementEfficiency(w,data,b)>1);assert.ok(logisticsMetrics(w).supplyVisits>=2);});
test('large demand queues hold the existing job, cart and path budgets',()=>{const {w}=fixture();w.buildings=[];w.troops=[];for(let i=0;i<48;i++){const b=makeBuilding('farm',2+i%12*4,2+Math.floor(i/12)*5,data);b.harvestBonus=100;w.buildings.push(b);}w.buildings.push(makeBuilding('storehouse',24,30,data));for(let i=0;i<150;i++){const u=makeUnit('builder',data);u.x=1.5;u.y=1.5+i%30;w.troops.push(u);}run(w,100);const m=logisticsMetrics(w);assert.ok(m.activeJobs<=24&&m.visibleCarts<=10&&m.routeCache<=48&&m.intervalPathCalculations<=8);});
