// Dependency-free real-Chromium regression test. CI provides google-chrome.
// Local usage: CHROME_BIN=/path/to/chrome npm run test:browser
import {spawn} from 'node:child_process';
import {mkdtemp,rm,writeFile,mkdir,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,extname,resolve} from 'node:path';
import {createServer} from 'node:http';
import assert from 'node:assert/strict';
const root=resolve('dist'),profile=await mkdtemp(join(tmpdir(),'midnight-browser-'));
const server=createServer(async(req,res)=>{try{let path=decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\/midnights-manner\//,'');if(!path||path==='/')path='index.html';const file=resolve(root,path);if(!file.startsWith(root+'/'))throw Error('Invalid path');res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.json':'application/json','.css':'text/css','.png':'image/png','.svg':'image/svg+xml'})[extname(file)]||'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404);res.end('Not found');}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const port=server.address().port;
const chrome=spawn(process.env.CHROME_BIN||'google-chrome',['--headless=new','--no-sandbox','--disable-gpu','--remote-debugging-port=0',`--user-data-dir=${profile}`,'about:blank'],{stdio:['ignore','ignore','pipe']});
let ws;
try{
 const endpoint=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Chrome startup timeout')),20000);let log='';chrome.on('error',reject);chrome.stderr.on('data',chunk=>{log+=chunk;const match=log.match(/DevTools listening on (ws:\/\/\S+)/);if(match){clearTimeout(timer);resolve(match[1]);}});});
 ws=new WebSocket(endpoint);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j;});
 let seq=0;const pending=new Map(),errors=[];
 ws.onmessage=event=>{const response=JSON.parse(event.data);if(response.id){const cb=pending.get(response.id);if(cb){pending.delete(response.id);response.error?cb.reject(Error(JSON.stringify(response.error))):cb.resolve(response.result);}}else if(response.method==='Runtime.exceptionThrown')errors.push(response.params.exceptionDetails.text);};
 const send=(method,params={},sessionId)=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params,sessionId}));});
 const {targetId}=await send('Target.createTarget',{url:'about:blank'});
 const {sessionId}=await send('Target.attachToTarget',{targetId,flatten:true});
 const call=(method,params={})=>send(method,params,sessionId);
 await call('Runtime.enable');await call('Page.enable');await call('Emulation.setDeviceMetricsOverride',{width:1440,height:1100,deviceScaleFactor:1,mobile:false});
 await call('Page.navigate',{url:`http://127.0.0.1:${port}/midnights-manner/`});
 const evaluate=async expression=>{const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||'Browser evaluation failed');return r.result.value;};
 for(let i=0;i<100;i++){if(await evaluate('Boolean(window.midnightsManner)'))break;await new Promise(r=>setTimeout(r,100));}
 assert.ok(await evaluate('Boolean(window.midnightsManner)'),'game loaded');
 await mkdir('artifacts',{recursive:true});
 const screenshot=async name=>{const {data}=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});await writeFile(`artifacts/${name}.png`,Buffer.from(data,'base64'));};
 const waitFor=async expression=>{for(let i=0;i<100;i++){if(await evaluate(expression))return;await new Promise(r=>setTimeout(r,75));}throw Error('Timed out: '+expression);};
 const click=async selector=>{const point=await evaluate(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});if(!e||e.disabled||!e.getClientRects().length)throw Error('Unavailable '+${JSON.stringify(selector)});e.scrollIntoView({block:'nearest'});const r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};})()`);await call('Input.dispatchMouseEvent',{type:'mousePressed',...point,button:'left',clickCount:1});await call('Input.dispatchMouseEvent',{type:'mouseReleased',...point,button:'left',clickCount:1});};
 const tap=async point=>{await call('Input.dispatchMouseEvent',{type:'mousePressed',...point,button:'left',clickCount:1});await call('Input.dispatchMouseEvent',{type:'mouseReleased',...point,button:'left',clickCount:1});};
 assert.equal(await evaluate('window.midnightsManner.paused'),true,'welcome pauses simulation');
 await click('#begin');await waitFor('window.midnightsManner.ready');
 await screenshot('desktop');
 assert.equal(await evaluate('document.documentElement.scrollHeight > innerHeight'),false,'game has no document scrolling');
 const count=await evaluate('window.midnightsManner.snapshot().world.buildings.length');
 await click('[data-tab="build"]');await click('[data-build="farm"]');
 await tap(await evaluate('window.midnightsManner.project(2.5,2.5)'));
 assert.equal(await evaluate('window.midnightsManner.snapshot().world.buildings.length'),count,'preview does not spend');
 await click('#confirm-place');assert.equal(await evaluate('window.midnightsManner.snapshot().world.buildings.length'),count+1,'confirm builds once');
 await click('[data-action="close"]');await click('[data-tab="troops"]');await click('[data-gear="cart"]');await click('[data-level]');
 assert.equal(await evaluate('window.midnightsManner.snapshot().world.troops[2].gear'),'cart','equipment applies');
 assert.equal(await evaluate('window.midnightsManner.snapshot().world.troops[0].level'),2,'training applies');
 await click('#close-panel');
 // Manage a workplace from its map selection, then hire directly into it.
 // The starting warrior stands in front of the crop bed: tap its upper half.
 await tap(await evaluate('(()=>{const p=window.midnightsManner.project(7,10);return {x:p.x,y:p.y-40};})()'));
 await screenshot('workplace-selection');
 console.log('Workplace selection:',await evaluate('document.querySelector("#inspector").textContent'));
 await click('[data-action="assign"]');
 await click('[data-staff]');
 assert.ok(await evaluate('window.midnightsManner.snapshot().world.troops.find(t=>t.type==="farmer").workplace'),'worker assigned from workplace');
 await click('[data-release]');
 assert.equal(await evaluate('window.midnightsManner.snapshot().world.troops.find(t=>t.type==="farmer").workplace'),null,'release opens the job');
 await click('[data-recruit="farmer"][data-workplace]');
 assert.ok(await evaluate('window.midnightsManner.snapshot().world.troops.filter(t=>t.type==="farmer").at(-1).workplace'),'direct hire is assigned');
 await screenshot('workplace');
 await click('#close-panel');await click('[data-tab="story"]');await click('[data-mission="first-harvest"]');
 assert.ok(await evaluate('window.midnightsManner.snapshot().mission'),'expedition starts');
 await click('[data-tab="story"]');await click('[data-home]');assert.equal(await evaluate('window.midnightsManner.snapshot().mission'),null,'return restores home');
 await click('#raid');await waitFor('window.midnightsManner.snapshot().world.enemies.length > 0');
 await click('#pause');assert.equal(await evaluate('window.midnightsManner.paused'),true);await click('#opt-save');await click('#resume');
 await call('Page.reload');await waitFor('Boolean(window.midnightsManner)');await click('#begin');
 assert.equal(await evaluate('window.midnightsManner.snapshot().world.troops[0].level'),2,'level restored');
 assert.equal(await evaluate('window.midnightsManner.snapshot().world.troops[2].gear'),'cart','gear restored');
 await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:2,mobile:true});await new Promise(r=>setTimeout(r,200));
 await click('#recenter');
 assert.equal(await evaluate('document.documentElement.scrollWidth > innerWidth || document.documentElement.scrollHeight > innerHeight'),false,'phone canvas fills viewport without scrolling');
 const before=await evaluate('window.midnightsManner.camera()');
 await call('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:170,y:350,id:1,radiusX:3,radiusY:3}]});
 await call('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:240,y:395,id:1,radiusX:3,radiusY:3}]});
 await call('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 const after=await evaluate('window.midnightsManner.camera()');assert.ok(Math.abs(before.x-after.x)+Math.abs(before.y-after.y)>.1,'one finger pans');
 const zoomBefore=after.zoom;
 await call('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:140,y:360,id:1},{x:240,y:360,id:2}]});
 await call('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:100,y:360,id:1},{x:280,y:360,id:2}]});
 await call('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 assert.ok((await evaluate('window.midnightsManner.camera().zoom'))>zoomBefore,'two fingers zoom');
 await click('#recenter');await screenshot('mobile');
 await click('[data-tab="build"]');await screenshot('mobile-build');
 await click('#close-panel');
 await call('Emulation.setDeviceMetricsOverride',{width:844,height:390,deviceScaleFactor:2,mobile:true});await new Promise(r=>setTimeout(r,100));await click('#recenter');await screenshot('landscape');
 assert.equal(await evaluate('document.documentElement.scrollHeight > innerHeight'),false,'landscape has no scrolling');
 await click('[data-tab="troops"]');await click('[data-category="recruit"]');
 assert.ok((await evaluate('document.querySelectorAll("[data-recruit]").length'))>=20,'all professions retained');
 assert.deepEqual(errors,[],'no browser runtime errors');
 console.log(JSON.stringify({placementConfirmation:true,equipment:true,training:true,mission:true,raid:true,saveReload:true,portrait:true,landscape:true,touchPan:true,pinchZoom:true,consoleErrors:errors}));
}finally{ws?.close();chrome.kill();server.close();await new Promise(r=>setTimeout(r,300));await rm(profile,{recursive:true,force:true,maxRetries:3,retryDelay:100});}
