import {mkdir,rm,cp,writeFile,readFile,readdir} from 'node:fs/promises';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {version}=require('../package.json');
const root=new URL('../',import.meta.url),out=new URL('../dist/',import.meta.url);
await rm(out,{recursive:true,force:true});await mkdir(out,{recursive:true});
// Allowlist: only public game files ship. sw.js is generated below so the
// repo root (npm run dev) never serves a service worker — registration and
// precache exist in dist/ builds only.
for(const file of ['index.html','manifest.webmanifest','src','assets','data'])await cp(new URL(file,root),new URL(file,out),{recursive:true});
async function walk(url,prefix){const out=[];for(const e of await readdir(url,{withFileTypes:true})){if(e.isDirectory())out.push(...await walk(new URL(e.name+'/',url),prefix+e.name+'/'));else out.push(prefix+e.name);}return out;}
const files=await walk(out,'./');
files.push('./');
const sw=`// Generated by scripts/build.mjs — do not edit. Cache ${version}.
const CACHE='midnights-manner-v${version}';
const CORE=${JSON.stringify(files.filter(f=>!/sw\\.js$/.test(f)),null,1)};
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(c=>c.addAll(CORE)).then(()=>self.skipWaiting()));});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()));});
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);if(url.origin!==self.location.origin)return;event.respondWith(caches.match(event.request).then(hit=>{if(hit)return hit;return fetch(event.request).then(res=>{if(res&&res.ok){const copy=res.clone();caches.open(CACHE).then(c=>c.put(event.request,copy));}return res;}).catch(()=>caches.match('./index.html'));}));});
`;
await writeFile(new URL('sw.js',out),sw);
// Register the worker in the built page only (dev stays uncached).
let html=await readFile(new URL('index.html',out),'utf8');
if(!html.includes('sw.js'))html=html.replace('</body>','<script>if(\'serviceWorker\' in navigator){addEventListener(\'load\',function(){navigator.serviceWorker.register(\'./sw.js\').catch(function(){})});}</script></body>');
await writeFile(new URL('index.html',out),html);
await writeFile(new URL('.nojekyll',out),'');
console.log(`Static game built in dist/ (sw cache midnights-manner-v${version}, ${files.length} precached)`);
