import {mkdir,rm,cp,writeFile,readFile,readdir} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {precacheFiles} from './precache-files.mjs';
import {assertReleaseRights,assertCatalogProvenance,contentBuildId} from './build-policy.mjs';
const require=createRequire(import.meta.url);
const {version}=require('../package.json');
const root=new URL('../',import.meta.url),out=new URL('../dist/',import.meta.url);
const localPreview=process.argv.includes('--local-preview');
const manifest=JSON.parse(await readFile(new URL('data/art-manifest.json',root),'utf8')),external=JSON.parse(await readFile(new URL('data/external_assets.json',root),'utf8'));
assertReleaseRights(manifest,localPreview,external);
async function walk(url,prefix){const out=[];for(const e of await readdir(url,{withFileTypes:true})){if(e.isDirectory())out.push(...await walk(new URL(e.name+'/',url),prefix+e.name+'/'));else out.push(prefix+e.name);}return out;}
if(!localPreview)await assertCatalogProvenance(manifest,external,await walk(new URL('assets/meshes/',root),'./assets/meshes/'),file=>readFile(new URL(file,root),'utf8'));
await rm(out,{recursive:true,force:true});await mkdir(out,{recursive:true});
for(const file of ['index.html','manifest.webmanifest','src','assets','data','mockups'])await cp(new URL(file,root),new URL(file,out),{recursive:true});
const allFiles=(await walk(out,'./')).sort(),files=precacheFiles(allFiles);
const worker=await readFile(new URL('./service-worker.js',import.meta.url),'utf8');
// Source hashes make code/data/art-only deploys discoverable without a version bump.
const seed=version+worker+(await readFile(new URL(import.meta.url)))+(await readFile(new URL('./build-policy.mjs',import.meta.url)));
const build=`${version}-${await contentBuildId(seed,allFiles,file=>readFile(new URL(file,out)),[...files,'./'])}`;
let html=await readFile(new URL('index.html',out),'utf8');
html=html.replace('</head>',`<meta name="game-build" content="${build}"></head>`);
await writeFile(new URL('index.html',out),html);
files.push('./');
const sw=`// Generated by scripts/build.mjs. Build ${build}.\nconst PREFIX='midnights-manner:'+self.registration.scope+':';\nconst CACHE=PREFIX+${JSON.stringify(build)};\nconst CORE=${JSON.stringify(files)};\n${worker}`;
await writeFile(new URL('sw.js',out),sw);
await writeFile(new URL('.nojekyll',out),'');
console.log(`Static game built in dist/ (build ${build}, ${files.length} precached${localPreview?', LOCAL PREVIEW ONLY':''})`);
