import {battlefieldStatus} from './systems/siege.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function battleControls(g){
 if(g.state.mission)return '';
 const posts=g.world.buildings.filter(b=>b.hp>0&&b.remaining<=0&&(['hall','gate','tower','archer_tower','grand-watchtower','storehouse','grand-granary'].includes(b.type)));
 return `<article class="adv-card" data-battle-controls><div class="adv-eyebrow">BATTLEFIELD COMMAND</div><h3>Hold the village</h3><label>Fighters <select data-battle-scope aria-label="Command group"><option value="all">All fighters</option><option value="melee">Melee line</option><option value="ranged">Ranged support</option></select></label><label>Post <select data-battle-post aria-label="Command post">${posts.map(b=>`<option value="${esc(b.id)}">${esc(g.data.buildings[b.type].name)} · ${b.x}, ${b.y}</option>`).join('')}</select></label><div class="actions"><button data-battle-command="hold">Hold</button><button data-battle-command="defend" ${posts.length?'':'disabled'}>Defend post</button><button data-battle-command="rally" ${posts.length?'':'disabled'}>Rally &amp; hold</button><button data-battle-command="auto">Resume group duties</button></div><p>Commands replace orders for this group. Away fighters and emergency duties keep priority. Defend intercepts within six tiles of the post; Rally gathers and holds. Resume releases only group orders.</p>${battleReadout(g.world,g.data)}</article>`;
}
export function battleReadout(w,d){const s=battlefieldStatus(w,d);return s.groups.length?`<p>Enemy plans: ${s.groups.map(g=>`${esc(g.side)} · ${g.count} ${g.phase==='muster'?'mustering':g.phase==='breach'?'exploiting a breach':'assaulting'} → ${esc(g.target)}`).join('<br>')}</p>`:'<p>The frontier is quiet.</p>';}
export function battleClick(g,b){if(!b.dataset.battleCommand)return false;const card=b.closest('[data-battle-controls]');g.commandGroup(b.dataset.battleCommand,card.querySelector('[data-battle-scope]').value,card.querySelector('[data-battle-post]').value);return true;}
