import {supplyDiagnostics} from './systems/logistics.js';
import {greatWorkTier} from './systems/roads.js';
import {resourceInfo} from './resources.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function supplyReadout(w,d){
 const view=supplyDiagnostics(w,d),idle=view.workshops.filter(b=>b.state!=='working');
 const projects=[['grand-granary','Granary','food load/unload'],['forge-quarter','Forge Quarter','industrial load/unload'],['market-square','Market Square','all load/unload']].filter(([id])=>greatWorkTier(w,id)>0);
 return `<article class="resource-detail"><small>WORKING SUPPLY CHAINS</small><h3>What the village needs</h3><p>Haulers prioritize meals, recovery, queued construction and equipment materials. Waiting jobs gradually gain priority. Workshops still spend from shared stores; delivery visits improve throughput.</p>${view.needs.length?view.needs.slice(0,6).map(n=>`<div class="source-row"><span>${esc(resourceInfo(n.resource).label)}<small>${n.reasons.map(esc).join(' · ')}</small></span><b>${Math.ceil(n.missing)} short</b></div>`).join(''):'<p>Current priority baskets are covered.</p>'}${idle.length?`<h4>Workshops waiting</h4>${idle.slice(0,6).map(b=>`<div class="source-row"><span>${esc(b.name)}<small>${esc(b.reason)}${b.missing.length?` · ${b.missing.map(k=>esc(resourceInfo(k).label)).join(', ')}`:''}</small></span><button data-event-focus="${esc(b.buildingId)}">View</button></div>`).join('')}`:''}${view.issues.length?`<h4>Delivery bottlenecks</h4>${view.issues.map(i=>`<div class="source-row"><span>${esc(resourceInfo(i.resource).label)}<small>${esc(i.reason)}</small></span><button data-event-focus="${esc(i.buildingId)}">View</button></div>`).join('')}`:''}${projects.length?`<p>Project benefits within eight tiles: ${projects.map(([id,label,action])=>`${label} +${Math.round(greatWorkTier(w,id)*(id==='grand-granary'?3:id==='forge-quarter'?2.5:1.5))}% ${action} speed`).join(' · ')}. Bonuses use the strongest applicable project, capped at +20%.</p>`:''}</article>`;
}
